name: Render ZIPs and Zcash Protocol Specification
description: GitHub Action to compile ZIPs and Zcash Protocol Specification LaTeX documents
author: Deirdre Connolly
runs:
  using: composite
  steps:
    - name: Render with nix build
      shell: bash
      run: |
        nix build
        cp -a ./result/rendered/. ./rendered/
        cp -a ./result/README.rst ./README.rst
